### ISSUE TITLE
Block when user try to add video with empty URL

### ISSUE THREAD

**Issue by RodrigoWebDev** [RodrigoWebDev/anonymous-youtube-playlist-generator#17]

**Comment by phadkesharan** [comment]
This issue is already solved. The URL is getting validated by using isAYoutubeURL function

**Comment by phadkesharan** [comment]
This issue is already solved. The URL is getting validated by using isAYoutubeURL function

**Comment by RodrigoWebDev** [comment]
Not resolved. Try to put a empy URL in the [app](https://anonymous-youtube-playlist-generator.netlify.app/) and you will see the bug:
![image](https://user-images.githubusercontent.com/30677819/170297239-fb81d73f-b87c-4014-a1f0-57684b5e3975.png)

**Comment by RodrigoWebDev** [comment]
You are right!
